name: demo_test1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  weather_icons: ^3.0.0
  pinput: ^3.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  image_picker: ^1.0.7
  country_picker: ^2.0.18
  fluttertoast: ^8.2.4
  photo_view: ^0.14.0
  url_launcher: ^6.2.4
  random_string: ^2.3.1
  firebase_messaging: ^14.7.14
  flutter_rating_bar: ^4.0.1
  rxdart: ^0.27.7
  flutter_local_notifications: ^16.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  geolocator: ^10.0.1
  weather: ^3.1.1
  intl: ^0.19.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/lanchicon.png"
  min_sdk_android: 21




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/image1.png
    - assets/image2.png
    - assets/image3.png
    - assets/Weather/1.png
    - assets/Weather/2.png
    - assets/Weather/3.png
    - assets/Weather/4.png
    - assets/Weather/5.png
    - assets/Weather/6.png
    - assets/Weather/7.png
    - assets/Weather/8.png
    - assets/Weather/9.png
    #- assets/Weather/10.png
    - assets/Weather/11.png
    - assets/Weather/12.png
    - assets/Weather/13.png
    - assets/images/horizontal_logo.png
    - assets/Weather/14.png
    - assets/images/your_logo.jpg
    - assets/images/Vege.png
    - assets/images/Potato.jpg
    - assets/images/Rice.jpg
    - assets/images/Lemon.jpg
    - assets/images/Weat.jpg
    - assets/images/Rectangle10.png
    - assets/images/Rectangle7.png
    - assets/images/Rectangle10.png
    - assets/images/Rectangle9.png
    - assets/images/Rectangle8.png
    - assets/images/Rectangle12.png
    - assets/images/Rectangle11.png
    - assets/images/vector.svg
    - assets/images/call.jpg
    - assets/images/img1.png
    - assets/images/Logo.png
    - assets/images/map.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
