// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl06fII7qv6iB9iRWfIfBw5mj_QUb6uiY',
    appId: '1:932017506304:web:7e9a9058f7e923614fb0e5',
    messagingSenderId: '932017506304',
    projectId: 'shetidhan-84856',
    authDomain: 'shetidhan-84856.firebaseapp.com',
    storageBucket: 'shetidhan-84856.appspot.com',
    measurementId: 'G-47BSE6R166',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACHNmybndWgP85uX2QVpHBPNi23zBoQvQ',
    appId: '1:932017506304:android:e8de0a1fee87f58b4fb0e5',
    messagingSenderId: '932017506304',
    projectId: 'shetidhan-84856',
    storageBucket: 'shetidhan-84856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1JO0_acevY9eII9x6JVuBWhaPcfPys9s',
    appId: '1:932017506304:ios:86e72c5a9f6c0c124fb0e5',
    messagingSenderId: '932017506304',
    projectId: 'shetidhan-84856',
    storageBucket: 'shetidhan-84856.appspot.com',
    iosBundleId: 'com.example.demoTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1JO0_acevY9eII9x6JVuBWhaPcfPys9s',
    appId: '1:932017506304:ios:5cedc29df69d3bfe4fb0e5',
    messagingSenderId: '932017506304',
    projectId: 'shetidhan-84856',
    storageBucket: 'shetidhan-84856.appspot.com',
    iosBundleId: 'com.example.demoTest1.RunnerTests',
  );
}
